file_cache:
  enabled: true
  content_cache:
    max_size_mb: 1024
    max_file_size_mb: 10
  tree_cache:
    persist_to_db: true
  metadata:
    track_access_stats: true
  watcher:
    enabled: true
    debounce_ms: 300
  binary_extensions:
    - .png
    - .jpg
    - .jpeg
    - .gif
    - .bmp
    - .ico
    - .webp
    - .svg
    - .mp3
    - .wav
    - .ogg
    - .flac
    - .aac
    - .mp4
    - .avi
    - .mov
    - .webm
    - .mkv
    - .zip
    - .tar
    - .gz
    - .7z
    - .rar
    - .exe
    - .dll
    - .so
    - .dylib
    - .pyc
    - .pyo
    - .class
    - .o
    - .obj
    - .pdf
    - .doc
    - .docx
    - .xls
    - .xlsx
    - .ppt
    - .pptx
    - .ttf
    - .otf
    - .woff
    - .woff2
    - .eot
  ignore_dirs:
    - node_modules
    - __pycache__
    - .git
    - .venv
    - venv
    - dist
    - build
    - .next
    - .nuxt
    - target
    - vendor
    - .idea
    - .vscode
    - .cache
    - coverage
